name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ui/package-lock.json
      - name: Cache ui dependencies
        uses: actions/cache@v4
        with:
          path: ui/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('ui/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install UI Dependencies
        run: cd ui && npm install
      - name: Build UI
        run: cd ui && npm run build
      - name: Install ripgrep
        run: sudo apt-get update && sudo apt-get install -y ripgrep
      - name: Install dolt
        run: |
          sudo bash -c 'curl -L https://github.com/dolthub/dolt/releases/latest/download/install.sh | bash'
          dolt config --global --add user.email "you@example.com"
          dolt config --global --add user.name "Your Name"
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: Run Tests
        run: cargo test
      - name: Run Clippy
        run: cargo clippy -- -D warnings
      - name: Check Formatting
        run: cargo fmt -- --check
